# Fuchsia City begins collecting...

```{=html}
<div style="font-family:monospace; font-size: 0.9em; background:#f0f0f0; border-left: 5px solid #4CAF50; padding: 0.75em 1em; margin-top: 1em; border-radius: 6px; width: fit-content;">
⬜ Developing Hypotheses<br>
🟩 <strong>Sample Collection</strong><br>
⬜ Outbreak Investigation<br>
⬜ Sequencing<br>
⬜ Bioinformatics<br>
⬜ Genomic Epidemiology <br>
⬜ Public Health Implementation
</div>


**Fuchsia City begins collecting swab samples from the animals, workers, and residents:**

Towards the end of January, upon the closing of the Safari Zone, hospitals began seeing a large increase of cases that exceeded their capacity for testing and treatment. All cases were tested for flu, but a large proportion of cases returned negative. The most doctors could do was send patients home with treatment unless it was a severe case that required hospitalization. Although it was difficult to ascertain the number of true cases in January, hospitals were now reporting cases in the thousands. 

The city set up additional testing for the animals and the residents. Given that the Safari Zone was filled with biodiversity, including thousands upon thousands of different animals, special clinics were established throughout different zones to try and capture as many animals that appeared ill. Animals that exhibited symptoms of fever, lethargy, and lack of appetite, were immediately swabbed and tested for flu. Typically, the residents that were experiencing moderate to severe symptoms would drop by the clinics for testing to receive the proper treatment for their illness. While few people tested positive for flu, most individuals and animals tested negative for flu. Doctors and animal trainers speculated that there must be a new pathogen spreading around the city and wildlife that’s not easily able to be detected using their known testing and sequencing protocols. After meeting to discuss the next course of action, doctors and animal trainers agreed to collect and archive as many swab samples as possible. Additionally, the group decided to reach out to the Regional Health Laboratory to inquire if they had the capacity to identify the pathogen in the samples. 

Fuchsia City had over a million residents and thousands of different animals inhabiting the Safari Zone. With so many potential sources of infection given the scale of the outbreak, the team of doctors and animal trainers had to decide how to approach sample collection. Should they test as many individuals and animals as possible, focusing on symptomatic cases, or target key locations where the virus might be circulating? The choice of sampling strategy could determine whether they identified the source...or missed it entirely.

## Discussion Two:

Based on the population size and structure, describe a sampling scheme that you think would best fit this outbreak scenario. What do we want to capture and how does your sampling scheme allow you to capture that? Some examples of sampling schemes include sequencing all samples,sequencing a set of random samples, or sequencing any sample that is available to you. 


