# Public Health Action



```{=html}
<div style="font-family:monospace; font-size: 0.9em; background:#f0f0f0; border-left: 5px solid #4CAF50; padding: 0.75em 1em; margin-top: 1em; border-radius: 6px; width: fit-content;">
⬜ Developing Hypotheses<br>
⬜ Sample Collection<br>
⬜ Outbreak Investigation<br>
⬜ Sequencing<br>
⬜ Bioinformatics<br>
⬜ Molecular Epidemiology <br>
🟩 <strong>Public Health Implementation</strong>
</div>

**Fuchsia City begins social distancing and masking:**

The Genomic Specialists Team met with Public Health Leadership to discuss their findings of the outbreak investigation. The Leadership was very surprised to hear the news of the source of the outbreak was due to a spillover event, but nonetheless was very quick to respond. “It seems that what we should do to mitigate future spread and transmission of this novel virus is to implement a city-wide masking and social distancing policy for the next couple of months.” Public Health Leadership also suggested setting up testing venues and working with researchers to develop treatment for the novel virus. They felt that it was important to make sure prevention and treatment coverage was thoroughly provided for the entire population of the city, to ensure that no one subset of the population was marginalized. This also included the animals of course. 

As the city began implementing public health action, news began to spread that a mystery flu-like illness was continuing to spread within other cities of the region. Public Health Leaders around the region were faced with the same situation of trying to curb the epidemic but had very little resources to do so. Many cities followed the public health measures that Fuchsia City had implemented, however lacked the resources to identify and track the novel virus. The Regional Health Lab was the only lab that currently possessed the capacity to sequence and identify the novel virus, so the Genomic Specialists worked together to construct a sentinel surveillance system to onboard genomic surveillance for this pathogen.

## Discussion Thirteen:

How would you construct a genomic surveillance system? Include in your discussion how you would obtain samples from laboratories. Would you use the sampling scheme discussed in Discussion One? 
