# The hidden source:

The team of Genomic Specialists met to discuss pathogen identification progress and updates on the outbreak investigation. Amid discussion, it was assumed that the mystery illness might have been picked up at the conference, but there’s no clear evidence that suggests that was, in fact, the case. Upon looking at the results of the case interviews, the specialists began to ask themselves, “What if the bat trainers were exposed prior to the conference? What could that exposure source be?” 

The investigation team had been operating under the assumption that the illness originated at the conference. But something wasn't adding up. Despite multiple confirmed cases among attendees, there was no evidence of a broader outbreak outside Fuchsia City before the conference. It appeared that many of the infected individuals might have had direct ties to the Safari Zone.

After a moment of silence, one of the team members finally spoke up. “Let’s test the bats” someone said. The team nodded in agreement, but one person was quick to speak up. “The bats did not appear to harbor any flu-like symptoms, and they appeared perfectly healthy according to the tests and physical examinations. “We should test the bats anyways!” exclaimed another team member.

## Discussion Eight:

Should you test the bats for the novel virus? If so, explain why. Additionally, if you decide to test the bats, should you use the older samples collected in December, new and recently collected samples, or both?


