project:
  type: book

book:
  title: "A Viral Genomics Outbreak Mystery"
  author: "Steph Lunn, MPH, MS"
  date: "4/10/2024"
  cover-image: images/nwpage_tree_logo.png
  repo-url: https://github.com/NW-PaGe/viral-genomics-workshop
  repo-actions: [edit, issue]
  chapters:
  - index.qmd
  - part: "Part 1"
    chapters: 
      - part1/index.qmd
      - part1/discussion.qmd
      - part1/quiz-test.qmd
  - part: "Part 2"
    chapters: 
      - part2/index.qmd
      - part2/quiz-test.qmd
  - part: "Part 3"
    chapters:
      - part3/index.qmd
      - part3/quiz-test.qmd
  - part: "Part 4"
    chapters:
      - part4/index.qmd
  - part: "Part 5"
    chapters:
      - part5/index.qmd
  - part: "Part 6"
    chapters:
      - part6/index.qmd
  - part: "Part 7"
    chapters:
      - part7/index.qmd
  - part: "Part 8"
    chapters:
      - part8/index.qmd
  - part: "Part 9"
    chapters:
      - part9/index.qmd
  - part: "Part 10"
    chapters:
      - part10/index.qmd
      - part10/quiz-test.qmd
  - part: "Part 11"
    chapters:
      - part11/index.qmd
      - part11/quiz-test.qmd
  - part: "Part 12"
    chapters:
      - part12/index.qmd
  - part: "Part 13"
    chapters:
      - part13/index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

