project:
  type: book

book:
  title: "Viral-geno"
  author: "Steph Lunn"
  date: "4/10/2024"
  cover-image: images/nwpage_tree_logo.png
  repo-url: https://github.com/NW-PaGe/viral-genomics-workshop
  repo-actions: [edit, issue]
  chapters:
  - index.qmd
  - part: "Part 1"
    chapters: 
      - part1/index.qmd
      - part1/discussion.qmd
  - part: "Part 2"
    chapters: 
      - part2/index.qmd
      - part2/discussion.qmd
  - part: "Part 3"
    chapters:
      - part3/index.qmd
      - part3/discussion.qmd
  - part: "Part 4"
    chapters:
      - part4/index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

