project:
  type: book

book:
  title: "A Viral Genomics Outbreak Mystery"
  author: "Steph M. Lunn, MPH, MS"
  date: "4/10/2024"
  cover-image: images/nwpage_tree_logo.png
  repo-url: https://github.com/NW-PaGe/viral-genomics-workshop
  repo-actions: [edit, issue]
  chapters:
  - index.qmd
  - intro.qmd
  - part: "Background"
    chapters: 
      - part1/index.qmd
      - part1/discussion.qmd
      - part1/quiz-test.qmd
  - part: "Sample Collection Part I"
    chapters: 
      - part2/index.qmd
      - part2/quiz-test.qmd
  - part: "Sample Collection Part II"
    chapters:
      - part3/index.qmd
      - part3/quiz-test.qmd
  - part: "Beginning the Investigation"
    chapters:
      - part4/index.qmd
  - part: "Pathogen Identification"
    chapters:
      - part5/index.qmd
  - part: "Pathogen Isolation"
    chapters:
      - part6/index.qmd
  - part: "Source Tracing"
    chapters:
      - part7/index.qmd
  - part: "Sequencing and Bioinformatics"
    chapters:
      - part8/index.qmd
  - part: "Quality Control Bioinformatics"
    chapters:
      - part9/index.qmd
      - part9/quiz-test.qmd
  - part: "Genomic Epidemiology"
    chapters:
      - part10/index.qmd
      - part10/quiz-test.qmd
  - part: "Public Health Implementation"
    chapters:
      - part11/index.qmd
      - part11/quiz-test.qmd
  - part: "Containing the Epidemic"
    chapters:
      - part12/index.qmd
  - part: "To the readers"
    chapters:
      - part13/index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

