on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - docs/**

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    env:
      RENV_PATHS_ROOT: ~/.cache/R/renv
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.22'
        
      - name: Prep CURL install
        run: sudo apt-get update

      - name: Install CURL Headers
        run: sudo apt-get install libcurl4-openssl-dev

      # - name: Setup Renv
      #   uses: r-lib/actions/setup-renv@v2
      
      # - name: Install extra R packages
      #   run: |
      #     install.packages(c("knitr", "rmarkdown", "quarto", "stringr"))
      #   shell: Rscript {0}
       

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2.0.2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
